"""Shared fixtures for bambuuzle tests."""

from __future__ import annotations

import hashlib
import json
import zipfile
from pathlib import Path

import pytest


SAMPLE_GCODE = """\
; generated by BambuStudio
G28 ; home all axes
M104 S200 ; set hotend temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S200 ; wait for hotend temp
G1 Z5 F3000 ; lift nozzle
G1 X100 Y100 F6000
G1 Z0.3 F1000
G1 X150 Y100 E10 F1500
G1 X150 Y150 E20 F1500
G1 X100 Y150 E30 F1500
G1 X100 Y100 E40 F1500
M104 S0 ; turn off hotend
M140 S0 ; turn off bed
G28 X Y ; home X Y
M84 ; disable motors
"""

SAMPLE_PLATE_JSON = {
    "plate_index": 0,
    "prediction": 120,
    "weight": 1.5,
    "outside": False,
    "bed_type": "auto",
}

CONTENT_TYPES_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType=\
"application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType=\
"application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
  <Default Extension="gcode" ContentType="text/x.gcode"/>
</Types>"""

RELS_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns=\
"http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" \
Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>"""

MODEL_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US"
  xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources/>
  <build/>
</model>"""

# A 1x1 red PNG (minimal valid PNG for thumbnail testing)
TINY_PNG = (
    b"\x89PNG\r\n\x1a\n"
    b"\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
    b"\x08\x02\x00\x00\x00\x90wS\xde"
    b"\x00\x00\x00\x0cIDATx\x9cc\xf8\x0f\x00\x00\x01\x01\x00\x05"
    b"\x18\xd8N\x00\x00\x00\x00IEND\xaeB`\x82"
)


def build_test_3mf(path: Path, gcode: str = SAMPLE_GCODE, plates: int = 1) -> Path:
    """Build a minimal .gcode.3mf test fixture at the given path."""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", CONTENT_TYPES_XML)
        zf.writestr("_rels/.rels", RELS_XML)
        zf.writestr("3D/3dmodel.model", MODEL_XML)

        for i in range(1, plates + 1):
            plate_gcode = gcode if i == 1 else f"; plate {i}\n{gcode}"
            gcode_bytes = plate_gcode.encode("utf-8")
            md5_hex = hashlib.md5(gcode_bytes).hexdigest()

            plate_meta = dict(SAMPLE_PLATE_JSON, plate_index=i - 1)

            zf.writestr(f"Metadata/plate_{i}.gcode", gcode_bytes)
            zf.writestr(f"Metadata/plate_{i}.gcode.md5", md5_hex)
            zf.writestr(f"Metadata/plate_{i}.json", json.dumps(plate_meta))
            zf.writestr(f"Metadata/plate_{i}.png", TINY_PNG)

    return path


@pytest.fixture
def tmp_3mf(tmp_path: Path) -> Path:
    """Create a single-plate test .gcode.3mf file."""
    return build_test_3mf(tmp_path / "test.gcode.3mf")


@pytest.fixture
def tmp_3mf_multiplate(tmp_path: Path) -> Path:
    """Create a two-plate test .gcode.3mf file."""
    return build_test_3mf(tmp_path / "test.gcode.3mf", plates=2)
